# [[main]]
# name = "Início"
# identifier = "home"
# weight = 100
# url = "/"

# [[main]]
# name = "Postagens"
# weight = 200
# identifier = "posts"
# url = "/post/"

# [[main]]
# name = "Portifólio"
# weight = 300
# identifier = "portfolio"
# url = "/portfolio/"

[[main]]
name = "Sobre"
weight = 400
identifier = "about"
url = "/about/"
