[[main]]
name = "Home"
identifier = "home"
weight = 10
url = "/"

[[main]]
name = "Code"
weight = 100
identifier = "code"
url = "/code/"

#[[main]]
#name = "Life"
#weight = 200
#identifier = "life"
#url = "/life/"

[[main]]
name = "Media"
weight = 200
identifier = "media"
url = "/media/"

[[main]]
name = "About"
weight = 400
identifier = "about"
url = "/about/"
