author = "Victor Toso"
description = "May all beings be happy."

mainSections = ["code", "media"]
mainSectionTitle = "Last posts about coding"
#showAllPostsOnHomePage = true
postsOnHomePage = 5
tagsOverview = true
#tocInline = true
showAllPostsArchive = true # or false (default)

copyright = "2022" # FIXME: Add some license here

colortheme = 'dark'
rss = true                        # show rss icon with link
avatar = "images/profile.webp"
monoDarkIcon = false            # show monochrome dark mode icon
disableHLJS = true              # disable requesting highlight.js

keywords = ""
favicon = "favicons/"
# example ["css/custom.css"]
customCss = []
# example ["js/custom.js"]
customJs = [] 
images = ["images/site-feature-image.png"]
doNotLoadAnimations = false

singleDateFormat = "2/1/2006"
indexDateFormat = "2/1/2006"
listDateFormat = "2/1/2006"
