title = "Victor Toso"
author = "Victor Toso"
copyright = "2022" # FIXME: Add some license here
#description = "Welcome my friend"
profilePicture = "images/profile.webp"
keywords = ""
favicon = "favicons/"
# example ["css/custom.css"]
customCss = []
# example ["js/custom.js"]
customJs = [] 
mainSections = ["post"]
images = ["images/site-feature-image.png"]
doNotLoadAnimations = false
# Google Fonts
#googleFonts = ["Indie+Flower", "Roboto:ital,wght@0,100;0,400;0,700;1,400"]
# Google Site Verify
#googleSiteVerify = "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789"
singleDateFormat = "2/1/2006"
indexDateFormat = "2/1/2006"
listDateFormat = "2/1/2006"
# Commento Comments
# CommentoURL = "https://commento.example.com/js/commento.js"
# Read More links for truncated summaries
# readMore = true
# postSectionName = "blog"

reversepagetitle = true # When set to 'true', the Window Title will be reversed to 'Title | Author' instead of the default 'Author | Title'

[simpleAnalytics]
# enable = true
# customurl = "https://analytics.example.com"

[plausibleAnalytics]
# domain = "example.com"
# serverURL = "https://analytics.example.com"

[umami]
# serverURL = "example.com"
# id = "94db1cb1-74f4-4a40-ad6c-962362670409"

## Math settings
[math]
enable = false  # options: true, false. Enable math support globally, default: false. You can always enable math on per page.
use = "katex"  # options: "katex", "mathjax". default is "katex".

## Social links
# use 'fab' when brand icons, use 'fas' when standard solid icons.
[[socialIcons]]
icon = "fab fa-twitter"
title = "Twitter"
url = "https://twitter.com/victortoso/"

[[socialIcons]]
icon = "fab fa-linkedin"
title = "Linkedin"
url = "https://www.linkedin.com/in/victortoso"

[[socialIcons]]
icon = "fab fa-github"
title = "GitHub"
url = "https://github.com/victortoso/"

[[socialIcons]]
icon = "fab fa-gitlab"
title = "GitLab"
url = "https://gitlab.com/victortoso/"

[[socialIcons]]
icon = "fab fa-linux"
title = "GNOME"
url = "https://gitlab.gnome.org/victortoso/"

[[socialIcons]]
icon = "fab fa-git"
title = "Freedesktop"
url = "https://gitlab.freedesktop.org/victortoso/"


[[socialIcons]]
icon = "fab fa-envelope"
title = "e-mail"
url = "mailto:me@victortoso.com"
